### ISSUE TITLE
Jegyzőkönyv

### ISSUE THREAD

**Issue by Mkriszti01** [Mkriszti01/RFT-project#13]
A jegyzőkönyv elkészült. 
Ennek megfelelően folytatódhat a fejlesztés.

**Comment by jcsili** [comment]
A jegyzőkönyvet átnéztem - az elírások javítása után - elfogadtam.

**Comment by SasAttila** [comment]
Én is elfogadtam!

**Comment by egibacsi** [comment]
Én is!!!
