### ISSUE TITLE
Ajánlatkérés

### ISSUE THREAD

**Issue by jcsili** [Mkriszti01/RFT-project#2]
Ajánlattevővel és ajánlattal szembeni követelmények részletezése elkészült.

**Comment by egibacsi** [comment]
Pontosan kell átnézni és odafigyelni minden részletre..
Nézzük át többen és többször is...ne maradjon ki semmi lényeges elem sem..

**Comment by jcsili** [comment]
Az ajánlatkéréssel dec. 20-ig meg kellene lenni, a "Követelmény specifikációval" együtt.

**Comment by egibacsi** [comment]
Pontosan kell átnézni és odafigyelni minden részletre..
Nézzük át többen és többször is...ne maradjon ki semmi lényeges elem sem..
