### ISSUE TITLE
Karakterkészlet

### ISSUE THREAD

**Issue by jcsili** [Mkriszti01/RFT-project#4]
A meglévő fájlok szerkesztése notepad++ -ban történt. A jelenlegi kódolás ANSI. Szerintem inkább UTF-8-ra állítsuk át. Vélemények? Nálatok hogyan jelenik meg a jelenlegi szöveg?

**Comment by Mkriszti01** [comment]
A GitHub desktopban az ékezetes betűk nem jelennek meg. Amikor a notepad++ -ban  átállítottam a kódolást a már meglévőknél az ékezetes karakterek szétestek...
Az árajánlatot elkezdtem és itt beállítottam a javaslatokat. Ez teljesen jól jelenik meg a desktopon is.

**Comment by jcsili** [comment]
Nálam még mindig gond van az ékezetes betűkkel, átrakom UTF-8 kódolásra, és javítom az eddigieket.
Remélhetőleg így mindenhol jól fog megjelenni!

**Comment by egibacsi** [comment]
nálam is voltak-vannak gondok az ékezetes karakterekkel...én is átnézem az egész projectet..
