### ISSUE TITLE
Színjavaslatok css

### ISSUE THREAD

**Issue by SasAttila** [Mkriszti01/RFT-project#6]
A képen látható színek csak tervek, nagyon szívesen várom a  szín javaslataitokat, ajánlom az Adobe Color Oldalt, mert ott téma szerint is tudtok választani illetve azonnal kiírja kódot ami alapján nekem könnyű módosítani

**Comment by egibacsi** [comment]
Szerintem a Projectnek harmonizálnia kell a szinekkel is...igy is jó benyomást teszünk a felhasználók felé.

**Comment by Mkriszti01** [comment]
Javaslataim az Adobe Color oldalról:
Bodegon Clara Peeters - elég barna, de a témához szerintem illene - 
SBP alt 5 - kék, logo1-hez jó lehet - 
prEven - szürke, szintén a logo1-hez -
Ingunns Julegave - szürke és kék - 

Vélemények?
