### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by SasAttila** [Mkriszti01/RFT-project#7]
Első körben a négyes számú logót gondoltam a weboldalra, mi a véleményetek róla maradhat vagy változtassak valamit?

**Comment by jcsili** [comment]
Nekem a 4-es és az 1-es logo tetszik, az 1-es jobban. Az oldalon lévő többi színtől függ, hogy melyik a jobb.

**Comment by jcsili** [comment]
A képernyőterveket látva, ha marad ez a szín, akkor maradjon a 4-es logo.

**Comment by egibacsi** [comment]
jók lesznek LOGO-k.
kell a design!!

**Comment by Mkriszti01** [comment]
Nekem az 1-es logo tetszik.

**Comment by SasAttila** [comment]
Rendben. A jelenlegi szín véglegesíthető? Narancs és logo 4. 

[a logo 1 halványabb szinekhez jó szerintem. ]

**Comment by Mkriszti01** [comment]
Lehetne a megbeszélés témája. Logo és szín.

**Comment by egibacsi** [comment]
szerintem is jó a két logo tervezet (1+4)....
legyen a 4-es..

**Comment by egibacsi** [comment]
A szín is jó lesz--ne legyen kirívó, de halovány sem!!!
A narancs jónak néz ki!!

**Comment by jcsili** [comment]
Attila! Rendben, maradjon a narancs és a 4. logo, véglegesíthető!

**Comment by SasAttila** [comment]
Rendben a narancs téma marad a 4-es logóval.

**Comment by Mkriszti01** [comment]
A logó belekerült a megbeszélés jegyzőkönyvébe.
